### ISSUE TITLE
How to log in to the admin account？You will be prompted with an incorrect email address

### ISSUE THREAD

**Issue by qkd90** [hyperledger/cello#419]
![image](https://user-images.githubusercontent.com/17605831/156538711-36663415-c0ba-449f-a70c-0e9796cff260.png)

**Comment by salikzquidz** [comment]
What about just register a new account?

**Comment by tan270du** [comment]
> What about just register a new account?

But I need an administrator account, how can a normal account become an administrator's permission?

**Comment by vectorccc** [comment]
请问解决了吗这个问题我也是相同的问题，注册用户登录不能创建节点，不知道是不是需要管理员登陆


>

**Comment by xXCHINNAXx** [comment]
**when you register a user the default role is admin**. You can check that with this api get call in browser http://localhost:8081/api/v1/users?format=json/

![image](https://user-images.githubusercontent.com/20676057/162669771-24d95b7a-d1d8-4835-a521-bca7ea516ff1.png)

and the default admin and pass are not working because the email is not configured properly see in line [17](https://github.com/hyperledger/cello/blob/476ced9358ed05eee95835c44a705a5da3e7b445/build_image/docker/common/api-engine/entrypoint.sh#L17), [17](https://github.com/hyperledger/cello/blob/476ced9358ed05eee95835c44a705a5da3e7b445/build_image/dockerhub/latest/common/api-engine/entrypoint.sh#L17). change the email from admin@cello => admin@cello.com and run all the make commands then the creds admin@cello.com, pass should work but as there is not default organisation you will see a blank page like below 

 
![image](https://user-images.githubusercontent.com/20676057/162672425-f83b921f-1131-42dd-a1e4-d3d9f3fd9a7c.png)

so I feel the line admin@cello is intestinal

**Comment by aesirteam** [comment]
Run into api_engine CONTAINER:

export ADMIN_EMAIL=admin@cello.com

python manage.py create_user \
    --username ${ADMIN_USERNAME:-admin} \
    --password ${ADMIN_PASSWORD:-pass} \
    --email ${ADMIN_EMAIL:-admin@cello} \
    --is_superuser \
    --role admin
