### ISSUE TITLE
admin account cant login

### ISSUE THREAD

**Issue by a893299419** [hyperledger/cello#533]
admin account can't login
<img width="539" alt="image" src="https://github.com/hyperledger/cello/assets/35991166/7baca0d2-27b8-4276-8c31-9e3b35f7520d">

## Expected Behavior

make docker
make start
## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

* OS:ubuntu
* Architecture:
* Docker version:
* Docker compose version:
* Kubernetes version:

**Comment by FatmaMahmoud698** [comment]
me too I have the same problem

**Comment by zhuyuanmao** [comment]
We have discussed this in the last weekly meeting, @xichen1 would you mind taking a look at this issue?

**Comment by xichen1** [comment]
> We have discussed this in the last weekly meeting, @xichen1 would you mind taking a look at this issue?

Sure, I've fixed it locally so the login issue is supposed to be solved after merging the change. But I have a question before creating the pr. Although I can login as the admin, I cannot operate anything using the admin user because there is nothing on the page. So just want to confirm is this what we want?

<img width="1510" alt="Screenshot 2023-08-09 at 1 14 06 PM" src="https://github.com/hyperledger/cello/assets/47851834/e347d708-038b-4a10-b426-7669b7034b97">

**Comment by flyforfreedom** [comment]
I met the same problem.

**Comment by zhuyuanmao** [comment]
Closed it as fixed
