### ISSUE TITLE
I tried to pull the h3c branch, and I reported an error after executing the make docker command

### ISSUE THREAD

**Issue by Zsilence07** [hyperledger/cello#588]
When I used the make docker command following the README-H3C.md document, it reported the following error
![01](https://github.com/hyperledger/cello/assets/125250518/320125b0-6a26-462c-9576-ef9c379323db)
Then I tried to execute the make setup-master command directly, but failed to find the image on the dockerhub when pulling the image. Where should I get the image?
![02](https://github.com/hyperledger/cello/assets/125250518/d9bbdeaf-b08b-4de1-b41a-86946454e82c)

**Comment by BlackFlame33** [comment]
第一个错我遇到过，这是因为react-draggable的最新版有[问题](https://github.com/react-grid-layout/react-draggable/issues/732)，去package.json修改react-draggable的版本为"4.4.5"再执行make docker就好了，这对我有效。
I've encountered the first error, it's because the latest version of react-draggable has a problem, go to package.json and change the version of react-draggable to "4.4.5" and then go to make docker and it's fine, it works for me!
